config/routes.rb
Rails.application.routes.draw do

	root "events#index"
	

	get '/login', to: 'sessions#new'
	post '/login', to: 'sessions#create'
	delete '/logout', to: 'sessions#destroy'

	resources :users
	resources :events

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :creator, class_name: "User", foreign_key: "user_id"
	has_and_belongs_to_many :attendees, class_name:"User"

	validates :name, presence: true
	validates :date, presence: true
	validates :presence, presence: true
	validates :place, presence: true

end

app/models/user.rb
class User < ApplicationRecord
	has_many :created_events, class_name: "Event"
	has_and_belongs_to_many :attended_events, class_name: "Event"

	before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  #permet de changer le password and password_digest. Il faut ajouter password_digest dans la table
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

    def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new
  	@event = Event.new
  end

  def create
  	@event = Event.new(params_event)
    @event.creator = current_user

  	if
  		@event.save
      flash[:success] = "Votre événement a bien été créé !"
  		redirect_to @event
  	else
  		redirect_to events_path
  	end
  end

  def show
    @event = Event.find(params[:id])
  end
end

private
  def params_event
   params.permit(:name, :description, :date, :place)
  end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
    	log_in user
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end 

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@users = User.all
	end

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params_user)
  	if @user.save
      log_in @user
      flash[:success] = "Bienvenu sur eventbritelike!"
  		redirect_to @user
  	else
  		render "new"
  	end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

    private
  def params_user
    params.permit(:name, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Returns the current logged-in user (if any).
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Evenements futurs</h1>

<p>Bienvenu sur la page d'accueil qui rassemble l'ensemble des événements à venir</p>

<% @events.each do |event| %>

<%= event.name %>
<%= event.date.strftime("%d-%m-%Y") %>
<%= event.place %>
<%= event.description %>
<%= event.creator.name %>
<%= link_to "Voir l'événement", event_path(event) %> </br>
<% end %>

<%= link_to "Créer un événement", new_event_path %>

app/views/events/new.html.erb
<% if logged_in? %>

	<h1>Créer un nouvel événement</h1>

	<%= form_tag (events_path) do %>  
	<% if @event.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@event.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
        <% @event.errors.full_messages.each do |msg| %>
          <p><%= msg %></p>
        <% end %>
    </div>
  <% end %> 
	  	<%= label_tag 'name', "Nom de l'évenement" %> 
		<%= text_field_tag 'name' %> 

		<%= label_tag 'date', "Date de l'événement" %> 
		<%#si marche aps mettre date_field %>
		<%= date_field_tag(:date) %>

		<%= label_tag 'place', "Lieu de l'évenement" %> 
		<%= text_field_tag 'place' %> 

		<%= label_tag 'description', "Description de l'événement" %> 
		<%= text_field_tag 'description' %>

		<%= submit_tag "Créer un nouvel événement"%> 
	<% end %>

<% else %>

	<p> Vous n'êtes pas connecté! </br>
	Connectez-vous afin de pouvoir créer un événement </br>
	<%= link_to "Connectez-vous maintenant", login_path %></p>
<% end %>

app/views/events/show.html.erb
<h1>Bienvenu sur l'événement</h1>

<p>
  <strong>Evenement:</strong>
  <%= @event.name%>
</p>
 
<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Lieu:</strong>
  <%= @event.place %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Créateur de l'événement:</strong>
  <%= @event.creator.name %>
</p>

<p>
  <strong>Liste des invités</strong>
  <% @event.attendees.each do |attendee| %>
  <%= attendee.name %>
  <%= link_to('Voir le profil du participant', user_path(attendee)) %>
  <% end %>
</p>

<%= link_to "Tous les événements", events_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "eventbritelike", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", '#' %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Eventbritelike</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                                              'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
    <%= render 'layouts/header' %>
    <div class="container">
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>Bienvenu sur la page d'accueil</h1>

<p><%= link_to "Créer un nouvel utilisateur" %><p>

app/views/users/new.html.erb
<h1>Créer un nouvel utilisateur</h1>

<%= form_tag (users_path) do %>   
  	<%= label_tag 'name', "Nom de l'utilsateur" %> 
	<%= text_field_tag 'name' %> 

	<%= label_tag 'email', 'Email' %> 
	<%= text_field_tag 'email' %>

	<%= label_tag 'password', 'Mot de passe' %> 
	<%= password_field_tag 'password' %>
	
	<%= submit_tag "Créer nouvel utilisateur"%> 
<% end %>

app/views/users/show.html.erb
  <h1>Profil de <%= @user.name%></h1>
 
<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
<strong>Liste des événements de l'utilisateur:</strong> <br>
	<% @user.created_events.each do |event| %>
  	<%= link_to event.name, event_path(event) %>
  	<%= event.date %> <br>
	<% end %>
</p>

<p>
 	<strong>Evenements auquel l'utilisateur participe</strong>
	<% @user.attended_events.each do |event|%>
 		<%= link_to event.name, event_path(event) %>
 		<%= event.date %> <br>
  <% end %>
</p>

<p><%= link_to "Clickez ici pour ajouter une activité", new_event_path %> </p>